### ISSUE TITLE
Hello, about the choice of camera

### ISSUE THREAD

**Issue by Allen070206** [javieryu/nerf_bridge#10]
I am a student from China, I can not buy the camera you introduced, could you please tell me what other type of camera I can choose.

**Comment by javieryu** [comment]
I recently have switched to using this camera: https://www.uctronics.com/arducam-global-shutter-color-usb-1mp-ov9782-uvc-webcam-module.html . At some point I plan on updating the README.

Theoretically, any RGB camera should work. Anything with a global shutter would be best because you want to avoid motion blur from rolling shutter.

**Comment by Allen070206** [comment]
Thank you, Sir. Good luck with your research！
