### ISSUE TITLE
Do you plan to update to ROS2?

### ISSUE THREAD

**Issue by abubake** [javieryu/nerf_bridge#29]
Hi, I was wondering if you have any plans to update this to ROS2 eventually as ROS1 will eventually become deprecated. Thanks!

**Comment by javieryu** [comment]
Check out the ROS2 branch! Everything there should be stable for 0.3.4 nerfstudio. I've been hoping to push a big update to that branch to upgrade to nerfstudio 1.0 and add gaussian splatting, but I haven't had a chance to upgrade the docs and do more thorough testing so that will take a couple more days.

**Comment by abubake** [comment]
That's awesome! I will check it out.
