### ISSUE TITLE
About pose messages

### ISSUE THREAD

**Issue by gotochen** [javieryu/nerf_bridge#7]
Which parameters should I provide if I use mine pose topic？

**Comment by javieryu** [comment]
All you need to do is change the name of the topic in the config.json (see [nsros_config_sample.json](https://github.com/javieryu/nerf_bridge/blob/25d459cd118390c7117923c341aba311aff54697/nsros_config_sample.json)) file you provide when you run NerfBridge. 

The other consideration is that you will need to transform your poses into the coordinate convention of ORBSLAM3 (NerfBridge will then convert them to Nerfstudio convention). Otherwise, you can also fork the repository and add your own coordinate transformations to `nsros/dataloader.py` in the appropriate locations.

**Comment by javieryu** [comment]
Closing this now. Feel free to re-open if you have other questions about specifying pose topics.
